name: Oracle Schema Validation

on:
  workflow_run:
    workflows: ["SQL Linting"]
    types:
      - completed

jobs:
  validate-oracle-schema:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      ORACLE_HOST: localhost
      ORACLE_PORT: 1521
      ORACLE_SERVICE: XE
      ORACLE_USER: system
      SCHEMA_USER: wmagent

    services:
      oracle:
        image: gvenzl/oracle-xe:18.4.0-slim
        env:
          ORACLE_USER: ${{ env.ORACLE_USER }}
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
          APP_USER: ${{ env.SCHEMA_USER }}
          APP_USER_PASSWORD: ${{ secrets.SCHEMA_PASSWORD }}
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period=60s

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Oracle
        run: |
          max_retries=5
          counter=0
          CONTAINER_ID=$(docker ps -q --filter "ancestor=gvenzl/oracle-xe:18.4.0-slim")
          echo "Waiting for Oracle to be ready..."

          while [ $counter -lt $max_retries ]; do
            counter=$((counter + 1))
            echo "Attempt $counter/$max_retries:"

            echo "1. Testing connection from inside container..."
            if docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << EOF
            SELECT 1 FROM dual;
            exit;
            EOF
            then
              echo "Oracle is ready!"
              exit 0
            fi

            echo "2. Container logs:"
            docker logs $CONTAINER_ID

            if [ $counter -eq $max_retries ]; then
              echo "Error: Maximum retries reached. Oracle connection failed."
              exit 51
            fi

            echo "Waiting 10 seconds before next attempt..."
            sleep 10
          done

      - name: Test Oracle Connection
        run: |
          echo "Testing Oracle connection..."
          CONTAINER_ID=$(docker ps -q --filter "ancestor=gvenzl/oracle-xe:18.4.0-slim")
          docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << 'EOF'
          WHENEVER SQLERROR EXIT SQL.SQLCODE;
          WHENEVER OSERROR EXIT 9;
          SET ECHO ON
          SET FEEDBACK ON
          SET HEADING ON
          SELECT 1 FROM dual;
          SELECT sys_context('USERENV', 'SESSION_USER') FROM dual;
          SELECT status FROM v\$instance;
          EXIT SUCCESS
          EOF

      - name: Deploy WMBS Schema
        run: |
          CONTAINER_ID=$(docker ps -q --filter "ancestor=gvenzl/oracle-xe:18.4.0-slim")
          echo -e "\nDeploying WMBS tables..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/wmbs/oracle/create_wmbs_tables.sql

          echo -e "\nDeploying WMBS indexes..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/wmbs/oracle/create_wmbs_indexes.sql

          echo -e "\nInitializing WMBS data..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/wmbs/oracle/initial_wmbs_data.sql

      - name: Deploy Agent Schema
        run: |
          echo -e "\nDeploying Agent schema..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/agent/oracle/create_agent.sql

      - name: Deploy DBS3Buffer Schema
        run: |
          echo -e "\nDeploying DBS3Buffer schema..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/dbs3buffer/oracle/create_dbs3buffer.sql

      - name: Deploy BossAir Schema
        run: |
          echo -e "\nDeploying BossAir schema..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/bossair/oracle/create_bossair.sql

      - name: Deploy ResourceControl Schema
        run: |
          echo -e "\nDeploying ResourceControl schema..."
          docker exec $CONTAINER_ID sqlplus system/${ORACLE_PASSWORD}@localhost:1521/XE @sql/resourcecontrol/oracle/create_resourcecontrol.sql

      - name: Verify Schema Deployment
        run: |
          echo -e "\nChecking table structure..."
          docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << EOF
          SET LINESIZE 200
          SET PAGESIZE 1000
          SELECT table_name, tablespace_name 
          FROM all_tables 
          WHERE owner = UPPER('${SCHEMA_USER}')
          ORDER BY table_name;
          EXIT;
          EOF

          echo -e "\nChecking indexes..."
          docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << EOF
          SET LINESIZE 200
          SET PAGESIZE 1000
          SELECT table_name, index_name, index_type
          FROM all_indexes
          WHERE owner = UPPER('${SCHEMA_USER}')
          ORDER BY table_name, index_name;
          EXIT;
          EOF

          echo -e "\nChecking foreign key relationships..."
          docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << EOF
          SET LINESIZE 200
          SET PAGESIZE 1000
          SELECT a.table_name, a.constraint_name, a.column_name,
                 c_pk.table_name r_table_name, b.column_name r_column_name
          FROM all_cons_columns a
          JOIN all_constraints c ON a.owner = c.owner
                               AND a.constraint_name = c.constraint_name
          JOIN all_constraints c_pk ON c.r_owner = c_pk.owner
                                  AND c.r_constraint_name = c_pk.constraint_name
          JOIN all_cons_columns b ON c_pk.owner = b.owner
                                AND c_pk.constraint_name = b.constraint_name
          WHERE c.constraint_type = 'R'
            AND a.owner = UPPER('${SCHEMA_USER}')
          ORDER BY a.table_name, a.column_name;
          EXIT;
          EOF

          echo -e "\nChecking initial data..."
          docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << EOF
          SET LINESIZE 200
          SET PAGESIZE 1000
          SELECT table_name, num_rows
          FROM all_tables
          WHERE owner = UPPER('${SCHEMA_USER}')
            AND num_rows > 0
          ORDER BY table_name;
          EXIT;
          EOF

      - name: Cleanup
        if: always()
        continue-on-error: true
        run: |
          if which sqlplus >/dev/null 2>&1; then
            echo "Running cleanup..."
            docker exec $CONTAINER_ID sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE << EOF
            DROP USER ${SCHEMA_USER} CASCADE;
            EXIT;
            EOF
            echo "Cleanup completed"
          else
            echo "SQLPlus not available, skipping cleanup"
          fi
