name: Release to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Matches x.y.z format
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Extract version from tag
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        fi

    - name: Update version in pyproject.toml
      run: |
        sed -i "s/version = \".*\"/version = \"${{ steps.version.outputs.version }}\"/" pyproject.toml

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          ## WMCore Database Schema v${{ steps.version.outputs.version }}
          
          This release contains database schema definitions for WMCore components,
          supporting both Oracle and MariaDB backends.
          
          ### Changes
          - Database schema files for WMBS, Agent, BossAir, DBS3Buffer, ResourceControl, TestDB, and Tier0
          - Support for Oracle and MariaDB backends
          - Data-only Python package for easy integration
          
          ### Installation
          ```bash
          pip install wmcoredb
          ```
          
          ### Usage
          ```python
          import pkg_resources
          
          # List SQL files in the package
          sql_files = pkg_resources.resource_listdir('wmcoredb', 'sql')
          
          # Get the path to a specific SQL file
          file_path = pkg_resources.resource_filename('wmcoredb', 'sql/mariadb/wmbs/create_wmbs_tables.sql')
          ```
        draft: false
        prerelease: false 